image:
  file: .gitpod.Dockerfile

tasks:
- init: ./mvnw clean install -DskipTests
  command: java -jar target/*.jar
  name: Run Foobartory

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot

jetbrains:
  intellij:  
    plugins:
      - MavenRunHelper
    prebuilds:
      version: both
